# Application Properties
spring:
  application:
    name: ecommerce-project
  data:
    rest:
      base-path: /api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: nikola
    password: nikola
    hikari:
      minimumIdle: 2
      maximumPoolSize: 100
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liL7ggyozwk6VubZ
            client-secret: 4e51e7079257f552ad29ab621b5b9f74583445ef
            scope: read:user,user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          google:
            client-id: 739617072960-fvkkbo5a5fplolh88mpu8kvuab6l151u.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          github:
            user-info-uri: https://api.github.com/user
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  servlet:
    session:
      timeout: 30m

application:
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
    max-age: 300

jwt:
  expiration-hours: 2
  secret-key: c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2